### PR TITLE
Getting Home Assistant to work with Russound (Some fixes / improvements)

### PR DESCRIPTION
**Pull request by acambitsis**
Hi Neil,

Firstly thank you for creating a Home Assistant integration with Russound.  It doesn't seem to be the most popular amp, so I am super appreciative that you created this.
When I recently configured the Russound_RNET component to work within HA, it wouldn't work.  So I started debugging.  The main issue was that the STATE_TURN_ON option was not defined in russound_rnet.py.  Adding this allowed it to work.  Since I started getting into the code, I also noticed that the device state and volume weren't actually being read from the amp itself.  Most of my other changes relate to making this change.  It was relatively easy to do since you already had the receive_data method in place.  It is not working perfectly, as there are some instances when the message returned when reading the power state is not what is expected, so I would be interested in discussing this further with you if you are willing.
Overall however, I have tested the changes and it seems to work well.  As mentioned above I have made changes to both russound.py in your repo as well as the russound_rnet.py within the HA repo.  The russound_rnet.py can be found on the HA fork I made - [here](https://github.com/acambitsis/home-assistant/blob/dev/homeassistant/components/media_player/russound_rnet.py).
I have not created a PR for that yet, as I wanted to get in touch with you first.
There is also someone else I came across on the forums (Sean - who I believe was in touch with you) who also wants to get this component working, and I am sure can help with some testing.
Lastly, I apologies if I made any stylistic changes to the code that you may not be happy with.  I am using PyCharm, and ended up obsessively responding to issues it highlighted.  Feel free to change accordingly.
Please let me know if you are ok to accept this PR (maybe as 0.1.7? and the best approach to get the full update into HA).
Many thanks,
Andreas.

### CODE REVIEW

**Comment by laf** [comment]
I actually came across the STATE_TURN_ON not on recently - it seems HASS has made some changes as it used to work without that. Enabled locally and it works so I was going to submit the change but please feel free to do so :)

Thanks for advancing this code, I wrote it quickly to be able to ditch using openremote so threw something together. I was planning to come back to state support but never had the time so I'm glad someone else found benefit from this and advanced it.

I'm in no way fussed about style in the code, I'm not a Python guy as you probably guessed so feel free to change what you want.

I'll test the code now and merge once done.

**Comment by laf** [comment]
Works for me using your patches to russound_rnet.py :)

Thanks again for contributing 👍 

If you can bump the version to 0.1.7 in setup.py and setup_pip.py then I'll merge and submit a new release. You'll then need to update the required version in your russound_rnet.py and submit a pull request to HASS. I think it will tag me for a review as I wrote the code so I'll comment and confirm it's working.

**Review by laf — APPROVED** [review]

**Comment by acambitsis** [comment]
Awesome Neil. Thanks for the prompt response. I'll be able to make the
changes you propose tomorrow. There is a bit more testing I will do as
well.
If there is anything you think could do with improvement let me know. I may
have time to add it.

Best regards,
Andreas.

**Comment by laf** [comment]
I found the volume status a little flakey, going to 0 and 100% when setting to various levels but it seemed 'inconsistent' so could be my side.

It would be nice to get the selected zone state up and running and displayed on hass widget but that's just a nice to have :)

**Comment by acambitsis** [comment]
Cool. Did some work on the selected zone last night and hope to complete
tonight. I also have had some ideas about making the socket comms more
robust (specifically the reading).  Will make sure I have that includes
before sending another PR.

**Comment by laf** [comment]
Thanks :)

I've sent you an invite to be a collaborator to this repo. Not sure what permissions this gives you but if it's enough to merge pull requests or push code changes directly then feel free to do so.

**Comment by acambitsis** [comment]
Ok great thanks for this.  I have spent a quite a bit of time today
refactoring and testing the code.  I am trying to make the reading of the
responses more reliable.  The RNET protocol seems to be quite a pain to
work with since you end up having response messages in the buffer that you
are not expecting at times.  I am trying to find the best way to get around
this without spending too much unnecessary time on read requests.  Will let
you know when done.

**Comment by laf** [comment]
Did you get the collaborator invite?

**Comment by acambitsis** [comment]
I did get it  thanks.  I'm finally done with the code changes and testing.
The selected source state is working and updating the HA UI.  The volume
level now also shows correctly on start up on the HA UI (it was incorrectly
defaulting to 0).  I have made the processing of the responses to determine
state, as robust as I can by checking for the specific message types.  So
even if the Russound controller returns multiple messages (which it does
under certain circumstances), it will still work correctly.
The HA UI is not as responsive as I would like it, but this may be an HA
issue combined with the fact that it has to poll.  The russound.py layer
processes commands within approx 300ms.  It is difficult to reduce this to
less because we need to wait at least 100ms for each call the Russound, and
we need to make two calls per command.
Anyhow - I need to get round to a few other things now, and I will try and
process a check-in directly in your repo later today.  I will however
create a branch and put the changes into that.  I will then create a PR.

**Comment by laf** [comment]
Wow, awesome work :)

I'll happily test this once you've pushed the code up as I'm sure the couple of others on HA who want to use it will.

**Pull request merged**
