### PR TITLE
fixes to threading, incomplete buffer and network traffic issues on e…

### PR DESCRIPTION
**Pull request by altersis**
…xisting version

As explained in bug #6, this is my proposal to address the issues found in the current version of Russound.py. I will separately request the Home Assistant folks for a pull of the optimized russound_rnet.py file that goes with this change. The details of the changes are as follows:

1. Home Assistant represents each Russound zone with an instance of a class periodically polls each zone zone status by calling the functions get_power/get_source/get_volume in russound.py, each call running on a different thread. The polling happens almost simultaneously for all zones, specially at startup. There was no synchronization mechanism on russound.py to ensure that one full call completes before a new request is written to the socket used to send the data to the serial gateway connected to the Russound device (I have a CAM6.6). The attached TCP stream capture (using wireshark) shows multiple message start delimiters being sent (F0's) at the same time, which the Russound device will interpret as an incorrect request.
russound tcp stream with garbled requests
**Changes to the code:** In order to synchronize access, I have added the use of a basic lock, and put a Try..catch..finally block to all functions that send/receive data. 

2. The find_signature function returns even if the all the data needed for the response has not been received (the portion of the message that contains the signature has been received but the part that contains the actual values requested has not been received).
**Changes to the code:** I have added a condition in find_signature to prevent breaking out of the loop if the whole response message has not been received yet. 

3. The Update method of RussoundRNETDevice on the Home Assistant file called russound_rnet.py calls get_power, get_source/get_volume functions in russound.py ; those three functions call the get_zone_info function, which translates into three identical requests to the Russound device with each call only using a different part of the response.
**Changes to the code**: Modified get_zone_info to return a list of ON-OFF/Source and Volume values whne invokes with a return_variable==4, and modified the UpdateStatus function in Home Assistant to call get_zone_info instead of making three separate calls. 

Thanks!

### CODE REVIEW

**Comment by laf** [comment]
Thank you so much for contributing back and sorry the code was bad in the first place :)

I'll need to get my HA -> Russound setup back up and running to test this, will aim to do so this weekend and feedback on this PR.

**Comment by altersis** [comment]
Thanks Neil, it is really my pleasure. I really look forward working with the hass community, so far as a user, the experience has been super good! I have initiated a pull request in your git page for russound.py, and I'm in the process of doing it on the hass side. I will send you the hass component code via email so that you can take a look.

Gerardo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acambitsis** [comment]
Hey @laf - I have been in touch with @altersis over the past few days to walk him through the process of submitting his changes.  He has done an amazing job in terms of getting up to speed with HASS and Python and with his strong foundations in CompSci and low level comms, he has really got to the bottom of the issues and done a thorough job of fixing them based on the code walk through he gave me.  I will also be testing the changes over the weekend and will report back.

**Comment by altersis** [comment]
[russound_rnet.zip](https://github.com/laf/russound/files/1342195/russound_rnet.zip)
Hi @laf, @acambitsis:
I'm attaching the russound_rnet.py file to allow you to test the fixes with Home Assistant. Submitting the changes to HomeAssistant is taking more than I expected, as there are a bunch of things that I have to learn to submit it (tox, virtualenvs, git in general, etc... sorry I have mostly been a TFS/Java/Delphi/C++ guy so far!). PLease feel free to contact me in case you have questions.

**Comment by acambitsis** [comment]
@laf , @altersis I have tested my set-up (Russound CAA66) and version 0.54 of HASS, with the russound.py and russound_net.py from this PR, and I am very happy to report that it works perfectly.  User experience is good (good response times) and there are no errors in the log file that I could see in relation to this.  Great job @altersis - I am happy for the PR to go through.

**Comment by laf** [comment]
@altersis If @acambitsis is happy with this then I'm happy (i've not had chance to test it today :( )

You will need to update setup_pip.py and setup.py to set a new version number (0.18) so that when you submit an update to HASS it can reference the new version.

@acambitsis Feel free to merge away when the setup files have been updated.

Thanks again to both of you for looking into this.

**Comment by acambitsis** [comment]
@laf happy with the below. A couple do things quickly. To the best of your
knowledge is it just the version number that needs to change in the setup
files you reference below?
In terms of publishing to pypi, I assume some process has to be kicked off?
I also assume it has to be done using your original pypi account? Unless
you delegate access?
Thanks,
Andreas.

**Comment by laf** [comment]
Yeah the version number needs changing and then a release creating on github.

I can add you to russound on pypi @acambitsis so you can publish the latest version if you like?

**Comment by acambitsis** [comment]
Ok so @laf I have merged @altersis' PR and bumped up the version of the setup files to 0.1.8.
I have also created a new release 0.1.8.
I think all that is left is to publish to pypi.  I am happy for you to do it (especially since you have done it before!), else I don't mind doing it if you are short of time and you give me access.
Many thanks,
Andreas.

**Comment by laf** [comment]
@acambitsis Done, but I'd like to get you access, let me know your pypi username and I'll add you.

**Comment by laf** [comment]
@altersis Thanks again for the fixes. Great work :)

**Comment by acambitsis** [comment]
Awesome.  Thanks for doing that.  I just registered on python.org - my
username is acambitsis.

**Comment by altersis** [comment]
No problem @laf. You guys had already done most of the work. Will now continue with the pr on HomeAssistant

**Comment by acambitsis** [comment]
@laf looks like we will need to re-publish to pypi.  I dont think I did the
merge of the PR correctly so not all the changes came through.  If you give
me access I'm happy to run with it from here.

**Comment by laf** [comment]
@acambitsis sure. What's your username there?

**Comment by acambitsis** [comment]
Its acambitsis

**Comment by laf** [comment]
Done :)

**Comment by acambitsis** [comment]
Awesome thanks.

**Comment by altersis** [comment]
PYPI doesn't allowed me to re upload version 0.1.8, so the code was bumped to 0.1.9, and has been successfully uploaded to pipi now. the Pull request on the Home Assistant side will now be submitted.

**Comment by laf** [comment]
Awesome work. Thanks again.

**Comment by altersis** [comment]
Gents, On the contrary, thanks to you. I have submitted to PR in home assistant. If you want to start using version 0.1.9 now, just modify the following line (18) in the Russound_rnet.py file that I want to believe you already have:

REQUIREMENTS = ['russound==0.1.7']

Change it to:

REQUIREMENTS = ['russound==0.1.9']

Then restart HA, it should bring the new package and allow you to enjoy. Cheers,

Gerardo


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by laf** [comment]
Just as an fyi, I've tested this now and it works well.

Thanks again :)

**Pull request merged**
